### ISSUE TITLE
Drop Count Tracking

### ISSUE THREAD

**Issue by jsnphil** [jsnphil/Kentobot#7]
- [ ] Mods can increment the stick drop count
- [ ] Users can view the stick drop count
- [ ] Mods can set the stick drop count to a specific number
