### ISSUE TITLE
Break Count Tracking

### ISSUE THREAD

**Issue by jsnphil** [jsnphil/Kentobot#8]
- [ ] Mods can increment the stick break count
- [ ] Users can view the stick break count
- [ ] Mods can set the stick break count to a specific number
